// eslint-config-next 16 ships native flat configs, so they are imported directly.
// (FlatCompat is not needed and in fact throws on this version.)
import nextCoreWebVitals from "eslint-config-next/core-web-vitals";
import nextTypescript from "eslint-config-next/typescript";

const config = [
  {
    ignores: [
      "node_modules/**",
      ".next/**",
      // Generated by `prisma generate`; not ours to lint.
      "src/generated/**",
      "coverage/**",
      "playwright-report/**",
      "test-results/**",
    ],
  },

  ...nextCoreWebVitals,
  ...nextTypescript,

  {
    files: ["src/core/**/*.ts"],
    rules: {
      // The pure core must stay free of framework imports — that separation is what makes the
      // scoring engine and every generator testable without a browser or a database, and it is
      // easy to break accidentally with a stray autocomplete import.
      "no-restricted-imports": [
        "error",
        {
          patterns: [
            {
              group: ["next", "next/*", "react", "react-dom", "@/generated/*", "@/server/*"],
              message:
                "src/core must not depend on the framework or the database client. Keep it pure.",
            },
          ],
        },
      ],
    },
  },
];

export default config;
