import { describe, expect, it } from "vitest";
import {
  blueprintIsSatisfiable,
  CORE_CATEGORIES,
  DIFFICULTY_BLUEPRINT,
  MAX_PER_CATEGORY,
  MAX_DISTINCT_CATEGORIES,
  MIN_DISTINCT_CATEGORIES,
  MIN_PER_CORE_CATEGORY,
  TEST_LENGTH,
  validateBlueprint,
} from "@/core/blueprint/blueprint";
import {
  AssemblyError,
  assembleTest,
  canSatisfyBlueprint,
  shuffleDelivery,
  type SamplerCandidate,
} from "@/core/blueprint/sampler";
import { buildBank } from "@/core/generation/bank";
import { createRng } from "@/core/generation/rng";
import { bandOf, CATEGORY_SLUGS, type CategorySlug } from "@/core/types";

/** A realistic pool, generated by the actual generators rather than hand-faked. */
function realisticPool(): SamplerCandidate[] {
  const bank = buildBank({ targetCount: 600, seed: "sampler-pool" });
  return bank.items.map((item, index) => ({
    questionId: `q${index}`,
    category: item.category,
    difficulty: item.difficulty,
  }));
}

const POOL = realisticPool();

describe("blueprint definition", () => {
  it("is internally consistent", () => {
    expect(blueprintIsSatisfiable()).toBe(true);
  });

  it("sums to the test length", () => {
    const total = Object.values(DIFFICULTY_BLUEPRINT).reduce((s, n) => s + n, 0);
    expect(total).toBe(TEST_LENGTH);
  });

  it("reserves at most the test length for core minimums", () => {
    expect(CORE_CATEGORIES.length * MIN_PER_CORE_CATEGORY).toBeLessThanOrEqual(TEST_LENGTH);
  });

  it("names exactly the six core domains from the specification", () => {
    expect([...CORE_CATEGORIES].sort()).toEqual(
      [
        "analogies",
        "logical-reasoning",
        "matrix-reasoning",
        "number-series",
        "pattern-recognition",
        "spatial-reasoning",
      ].sort(),
    );
  });
});

describe("blueprint validation", () => {
  function conformingTest(): { questionId: string; category: CategorySlug; band: ReturnType<typeof bandOf> }[] {
    const rng = createRng("conforming");
    return assembleTest(POOL, rng).map((i) => ({
      questionId: i.questionId,
      category: i.category,
      band: i.band,
    }));
  }

  it("accepts a conforming test", () => {
    expect(validateBlueprint(conformingTest())).toEqual([]);
  });

  it("rejects a test of the wrong length", () => {
    const codes = validateBlueprint(conformingTest().slice(0, 19)).map((v) => v.code);
    expect(codes).toContain("wrong-length");
  });

  it("rejects a duplicated question", () => {
    const items = conformingTest();
    items[1] = { ...items[0]! };
    expect(validateBlueprint(items).map((v) => v.code)).toContain("duplicate-question");
  });
});

describe("test assembly", () => {
  it("satisfies every blueprint constraint across many independent draws", () => {
    // One conforming test proves little; the constraints interact, so the sampler has to be
    // exercised repeatedly to show it never deadlocks or quietly violates a rule.
    for (let trial = 0; trial < 300; trial += 1) {
      const rng = createRng(`assembly:${trial}`);
      const test = assembleTest(POOL, rng);

      expect(validateBlueprint(test)).toEqual([]);
      expect(test).toHaveLength(TEST_LENGTH);

      // No repeats.
      const ids = test.map((i) => i.questionId);
      expect(new Set(ids).size).toBe(TEST_LENGTH);

      // Exact difficulty profile.
      const byBand = new Map<string, number>();
      for (const item of test) byBand.set(item.band, (byBand.get(item.band) ?? 0) + 1);
      expect(byBand.get("easy")).toBe(4);
      expect(byBand.get("medium")).toBe(8);
      expect(byBand.get("hard")).toBe(6);
      expect(byBand.get("very-hard")).toBe(2);

      // Category balance.
      const byCategory = new Map<CategorySlug, number>();
      for (const item of test) {
        byCategory.set(item.category, (byCategory.get(item.category) ?? 0) + 1);
      }
      expect(byCategory.size).toBeGreaterThanOrEqual(MIN_DISTINCT_CATEGORIES);
      expect(byCategory.size).toBeLessThanOrEqual(MAX_DISTINCT_CATEGORIES);
      for (const count of byCategory.values()) {
        expect(count).toBeLessThanOrEqual(MAX_PER_CATEGORY);
      }
      for (const core of CORE_CATEGORIES) {
        expect(byCategory.get(core) ?? 0).toBeGreaterThanOrEqual(MIN_PER_CORE_CATEGORY);
      }

      // The property that actually makes the results page useful: every category that appears
      // must carry enough items to say something about. A category represented by a single
      // question can only ever be reported as "too few questions to comment".
      for (const [category, count] of byCategory) {
        expect(count, `${category} appeared only ${count} time(s)`).toBeGreaterThanOrEqual(2);
      }

      // The band recorded on each item must match its difficulty.
      for (const item of test) expect(item.band).toBe(bandOf(item.difficulty));
    }
  });

  it("produces a different test for every attempt", () => {
    // The core promise to users: two people are extremely unlikely to see the same test.
    const signatures = new Set<string>();
    for (let trial = 0; trial < 200; trial += 1) {
      const test = assembleTest(POOL, createRng(`unique:${trial}`));
      signatures.add([...test.map((i) => i.questionId)].sort().join(","));
    }
    expect(signatures.size).toBe(200);
  });

  it("overlaps little between two independent tests", () => {
    let totalOverlap = 0;
    const trials = 100;
    for (let trial = 0; trial < trials; trial += 1) {
      const a = new Set(assembleTest(POOL, createRng(`ov-a:${trial}`)).map((i) => i.questionId));
      const b = assembleTest(POOL, createRng(`ov-b:${trial}`)).map((i) => i.questionId);
      totalOverlap += b.filter((id) => a.has(id)).length;
    }
    // Expected overlap for 20 draws from a 600-item pool is well under two items.
    expect(totalOverlap / trials).toBeLessThan(3);
  });

  it("is reproducible from its seed, so a delivered test can be audited", () => {
    const first = assembleTest(POOL, createRng("audit-seed"));
    const second = assembleTest(POOL, createRng("audit-seed"));
    expect(second.map((i) => i.questionId)).toEqual(first.map((i) => i.questionId));
  });

  it("honours the exclusion set when the remaining pool is large enough", () => {
    const previous = assembleTest(POOL, createRng("exclusion-a"));
    const exclude = new Set(previous.map((i) => i.questionId));

    const retake = assembleTest(POOL, createRng("exclusion-b"), { exclude });
    for (const item of retake) {
      expect(exclude.has(item.questionId)).toBe(false);
    }
    expect(validateBlueprint(retake)).toEqual([]);
  });

  it("still delivers a valid test when the exclusion set would make assembly impossible", () => {
    // Novelty is a preference, not a guarantee. A returning user who has seen nearly the whole
    // bank must still receive a well-formed test rather than an error.
    const excludeAll = new Set(POOL.map((c) => c.questionId));
    const test = assembleTest(POOL, createRng("exhausted"), { exclude: excludeAll });
    expect(validateBlueprint(test)).toEqual([]);
  });

  it("fails loudly when the pool genuinely cannot satisfy the blueprint", () => {
    const tooSmall = POOL.slice(0, 10);
    expect(() => assembleTest(tooSmall, createRng("tiny"))).toThrow(AssemblyError);
  });

  it("detects an unsatisfiable pool without attempting assembly", () => {
    expect(canSatisfyBlueprint(POOL)).toBe(true);
    // Remove every very-hard item: the blueprint needs two and cannot be satisfied.
    const noVeryHard = POOL.filter((c) => c.difficulty < 9);
    expect(canSatisfyBlueprint(noVeryHard)).toBe(false);
  });

  it("reports which constraint failed", () => {
    const noSpatial = POOL.filter((c) => c.category !== "spatial-reasoning");
    expect(() => assembleTest(noSpatial, createRng("no-spatial"))).toThrow(/spatial-reasoning/);
  });
});

describe("delivery shuffling", () => {
  it("assigns each question a unique consecutive position", () => {
    const test = assembleTest(POOL, createRng("delivery"));
    const counts = new Map(test.map((i) => [i.questionId, 4]));
    const delivery = shuffleDelivery(test, counts, createRng("delivery-shuffle"));

    expect(delivery).toHaveLength(TEST_LENGTH);
    expect(delivery.map((d) => d.position).sort((a, b) => a - b)).toEqual(
      Array.from({ length: TEST_LENGTH }, (_, i) => i),
    );
    expect(new Set(delivery.map((d) => d.questionId)).size).toBe(TEST_LENGTH);
  });

  it("permutes the options of each question without losing any", () => {
    const test = assembleTest(POOL, createRng("options"));
    const counts = new Map(test.map((i, idx) => [i.questionId, idx % 2 === 0 ? 4 : 5]));
    const delivery = shuffleDelivery(test, counts, createRng("options-shuffle"));

    for (const entry of delivery) {
      const expected = counts.get(entry.questionId)!;
      expect(entry.choiceOrder).toHaveLength(expected);
      // Every canonical ordinal must appear exactly once, or an option would be lost or doubled.
      expect([...entry.choiceOrder].sort((a, b) => a - b)).toEqual(
        Array.from({ length: expected }, (_, i) => i),
      );
    }
  });

  it("actually varies the option order across attempts", () => {
    const test = assembleTest(POOL, createRng("vary"));
    const counts = new Map(test.map((i) => [i.questionId, 4]));

    const orders = new Set<string>();
    for (let trial = 0; trial < 40; trial += 1) {
      const delivery = shuffleDelivery(test, counts, createRng(`vary:${trial}`));
      orders.add(delivery.map((d) => d.choiceOrder.join("")).join("|"));
    }
    expect(orders.size).toBeGreaterThan(30);
  });
});

describe("bank coverage supports the blueprint", () => {
  it("has enough items in every band and core category", () => {
    expect(canSatisfyBlueprint(POOL)).toBe(true);
    for (const category of CATEGORY_SLUGS) {
      expect(POOL.filter((c) => c.category === category).length).toBeGreaterThan(0);
    }
  });
});
